# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Make graphs application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Delete old generated graphs
      run: |
        rm -f data/graphs/interesting_differences/*.html
        rm -f data/graphs/interesting_total_count/*.html
        rm -f data/graphs/general/*.html
    - name: Make Graphs
      run: python src/graphs/make_graphs.py
    - name: Make summary
      run: python src/graphs/make_summary.py
    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/graphs/interesting_differences/*.html
        git add data/graphs/interesting_total_count/*.html
        git add data/graphs/general/*.html
        git add webapp/src/lib/data/summary.json
        git add webapp/src/lib/data/restaurants.json
        git add webapp/src/lib/data/restaurant-details.json
        git commit -m "Update generated graphs" || echo "No changes to commit"
        git push origin HEAD:main
